### PR TITLE
Add docs for PBS Pro

### PR DESCRIPTION
**Pull request by abhi18av**
This PR adds the documentation for PBS Pro.

The WIP documentation for Azure has been moved to [abhinav/azbatch](https://github.com/seqeralabs/nf-tower-docs/tree/abhinav/azbatch) branch so as to not to block the PBS Pro docs till the [Azure Forge feature](https://github.com/seqeralabs/nf-tower-cloud/issues/951) is added and ready to be documented.

### CODE REVIEW

**Comment by abhi18av** [comment]
This is how the the documentation for `PBS Pro` looks like as of now 

image

**Comment by pditommaso** [comment]
Ok, nice. Keep Azure in a separate PR, please.

**Comment by abhi18av** [comment]
@pditommaso , I've removed the Azure Batch from this PR after that screenshot. Good to go from my end, unless there are some other changes.

**Comment by pditommaso** [comment]
OK, looks good. Lets call it `Altair PBS Pro` instead `PBS Pro` even if it's a bit repetitive. Also, the page file name should be `altair-pbs-pro.md`.

**Comment by abhi18av** [comment]
Oki doki, I've implemented the change request 👍

**Comment by pditommaso** [comment]
Nice. Merging

**Pull request merged**
