### PR TITLE
fixed_site

### PR DESCRIPTION
**Pull request by venhrun-petro**

### CODE REVIEW

**Comment by ynestin** [comment]
@venhrun-petro Could you provide please a short description of what was changed?

**Comment by pditommaso** [comment]
@ynestin  Sorry, I should have provided more details. The goals were the ones described in #26, #29 and #30

**Comment by pditommaso** [comment]
@venhrun-petro  Just tried, I'm getting this error 

```
Switched to a new branch 'venhryn/fixed'
nf-tower-docs (venhryn/fixed)» hugo
Error: "/Users/pditommaso/Projects/nf-tower-docs/layouts/partials/head.html:1:1": parse failed: template: partials/head.html:1: illegal number syntax: "-"
```

**Review by ynestin — COMMENTED** [review]
I've noticed that along with the changes for https://github.com/seqeralabs/nf-tower-docs/issues/30 the `pointer` cursor that was shown on screenshot hover was removed. I think it should be returned. 
Considering https://github.com/seqeralabs/nf-tower-docs/issues/29 I still get some warnings: 

image

Not sure that they are crucial tho.

**Comment by evanfloden** [comment]
@pditommaso I think this can be closed correct?

**Comment by pditommaso** [comment]
Yes

**Pull request closed without merging**
