### PR TITLE
mkdocs-markdown-extradata doc variables plugin

### PR DESCRIPTION
**Pull request by llewellyn-sl**
Implementing a variable solution for URLs and values that need to get bumped with new Tower versions (such as the CR FE and BE image URLs that change for each version tag).

### CODE REVIEW

**Comment by pditommaso** [comment]
@llewellyn-sl continuing to edit this repo, we are going ahead a mess

**Comment by llewellyn-sl** [comment]
> @llewellyn-sl continuing to edit this repo, we are going ahead a mess

It's committed in this repo because it includes a tooling update. The config files for these docs are not in nf-tower-cloud. Publishing still happens from here, and this PR includes a plugin added to the docker image requirements.txt and mkdocs.yml.

**Comment by pditommaso** [comment]
Not really, all `docs` is in nf-tower-cloud 

https://github.com/seqeralabs/nf-tower-cloud/blob/9574c4ad0259886997e4d3f48e96b07567d16143/docs/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json

**Comment by llewellyn-sl** [comment]
>Not really, all docs is in nf-tower-cloud

Yes, all doc content is in the cloud repo, but the requirements.txt, mkdocs.yml are not. I made changes to the doc files themselves to test that the extradata plugin handles variable injection the way intended. I'll remove the doc updates from this PR and port them to nf-tower-cloud, opening a new PR there.

**Comment by llewellyn-sl** [comment]
@pditommaso Done. I stripped out the docs changes to the cloud repo and left just the config changes here. The comments chunk removed from fusion.md has been removed on the cloud repo side as well, so that does not introduce a delta.

**Review by gwright99 — APPROVED** [review]
LGTM

**Pull request merged**
