### PR TITLE
Add the documentation updates for k8s (specs) / EFS and NF Schema

### PR DESCRIPTION
**Pull request by pditommaso**
Sorry was to fast merging #81, I've reverted it. 

Let's replace "Nextflow Schema" with "Pipeline Schema"

### CODE REVIEW

**Comment by abhi18av** [comment]
@pditommaso , should I replace `Nextflow schema` -> `Pipeline schema` in the index or within the text as well?

**Comment by pditommaso** [comment]
Yep, thanks

**Comment by pditommaso** [comment]
I mean both index and schema

**Comment by abhi18av** [comment]
Paolo, I've accomodated the change request :)

**Pull request merged**
