### PR TITLE
Merge deployment docs

### PR DESCRIPTION
**Pull request by llewellyn-sl**
- Merging install docs content
- Adding Tower Enterprise to User docs left nav
- Grouping API, Agent and CLI pages under new Integration left nav section
- Lifting release notes and changelog out of Enterprise section into new Releases left nav section
- Adding Tower Legacy container images page for AWS, Azure, and GCP CRs under advanced topics.

### CODE REVIEW

**Comment by pditommaso** [comment]
There's no preview for those changes?

**Comment by llewellyn-sl** [comment]
>There's no preview for those changes?

Changes can be previewed locally with mkdocs serve:
image

 
image
image
image

**Comment by pditommaso** [comment]
Have you installed mkdocs locally? I was used to run `make serve` as described in the readme but it looks not working anymore

**Comment by gwright99** [comment]
I've been using `mkdocs serve` ever since I joined and started working with Abhinav on the docs. Not sure if anyone ever updated the `make` commands (I haven't).

**Comment by pditommaso** [comment]
This is what I get on master branch 

```
» make serve
docker run --rm -it -p 8000:8000 -v /Users/pditommaso/Projects/nf-tower-docs:/docs squidfunk/mkdocs-material:7.1.2
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: alternate_style 
ERROR   -  Config value: 'plugins'. Error: The "social" plugin is not installed 

Aborted with 2 Configuration Errors!
make: *** [serve] Error 1
```

Does it work for you?

**Comment by gwright99** [comment]
That catches everyone. Please delete the `.cache` folder at the root of the project and try again.

**Comment by pditommaso** [comment]
Same 

```
» rm -rf .cache/
» make serve
docker run --rm -it -p 8000:8000 -v /Users/pditommaso/Projects/nf-tower-docs:/docs squidfunk/mkdocs-material:7.1.2
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: alternate_style 
ERROR   -  Config value: 'plugins'. Error: The "social" plugin is not installed 

Aborted with 2 Configuration Errors!
make: *** [serve] Error 1
```

**Comment by gwright99** [comment]
Ok I see what happened - `make` is using an old container which causes all sorts of problems (it's based on Alpine Linux and some of the necessary packages need `gcc`). I've create a new container which loads, but breaks on a fontawesome icon issue. Will have fixed shortly.

**Comment by gwright99** [comment]
Try this please (it's not `make serve`) but it's close - I can update the Makefile later if need be:

```
$ gsts

$ ws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 128997144437.dkr.ecr.us-east-1.amazonaws.com

$ cd nf-tower-docs

$ docker run --rm -it -p 8000:8000 -v ${PWD}:/nf-tower-docs --entrypoint mkdocs --workdir /nf-tower-docs 128997144437.dkr.ecr.us-east-1.amazonaws.com/mkdocs-container:v2 serve --dev-addr=0.0.0.0:8000
```

**Comment by pditommaso** [comment]
```
docker: Error response from daemon: pull access denied for 128997144437.dkr.ecr.us-east-1.amazonaws.com/mkdocs-container, repository does not exist or may require 'docker login': denied: User: arn:aws:iam::195996028523:user/yo is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-east-1:128997144437:repository/mkdocs-container because no resource-based policy allows the ecr:BatchGetImage action.
```

**Comment by pditommaso** [comment]
Ok, let's merge this

**Comment by pditommaso** [comment]
Is the staging branch published somewhere?

**Comment by llewellyn-sl** [comment]
> Is the staging branch published somewhere?

@pditommaso I've published staging to the staging URL (https://nf-tower-user-docs-staging-html.netlify.app/) without error, but get a 404 when browsing to it. Will check with Oleh.

**Pull request merged**
