### PR TITLE
fix pipeline schema link & typo

### PR DESCRIPTION
**Pull request by alvaromartmart**
Fix invalid link to pipeline schema page

### CODE REVIEW

**Review by abhi18av — APPROVED** [review]
LGTM - thanks @alvaromartmart!

**Comment by abhi18av** [comment]
@pditommaso , a gentle reminder for this one too 😄

**Review by pditommaso — APPROVED** [review]
Nice!

**Comment by pditommaso** [comment]
Oops. there's a conflict can you have a look to it?

**Comment by abhi18av** [comment]
Sure, I've resolved the merge conflict now. Looks good to go ahead ✅

**Comment by pditommaso** [comment]
Cool 👍

**Pull request merged**
