### PR TITLE
Transition to docusaurus based docs

### PR DESCRIPTION
**Pull request by abhi18av**
**Todo**
- [ ] This PR might still to be updated for auto-deployment configs.
- [ ] Cleanup meta-data related to Hugo

To get this running locally, you'd need to do 

```
npm install -g yarn

yarn install

yarn start

```

### CODE REVIEW

**Comment by pditommaso** [comment]
In general, it looks quite good. A few notes: 
* are there other themes? colours of hint/warn/etc boxes could be better 
* previous/next navigation buttons at the bottom can be removed? 
* how to generate the static HTML?

**Comment by abhi18av** [comment]
>   how to generate the static HTML?

This can be achieved by simply doing `yarn run build` 
https://v2.docusaurus.io/docs/deployment


>    are there other themes? colours of hint/warn/etc boxes could be better

The colors of hint and warning could be customized by tweaking around the `CSS` , here are the packaged shades which can be configured   https://infima.dev/docs/utilities/colors **I'm working on the right combination now.**

>   previous/next navigation buttons at the bottom can be removed? 

I didn't find a way to do this, but the navigation is also present in the current website 

image

**Comment by abhi18av** [comment]
Okay, so I've understood how to customize the colors for the `admonitions` 

In the `src/css/custom.css` we need to tweak around with the following CSS classes.

Since this is related to `color/shade choice` please let me know which ones you feel fit in nicely and I'll configure them accordingly.

```css

.alert--success {
  --ifm-alert-background-color: var(--ifm-color-success-lighter);
}

.alert--info {
  --ifm-alert-background-color: var(--ifm-color-info-lighter);
}

.alert--note {
  --ifm-alert-background-color: var(--ifm-color-note-lighter);
}

.alert--warning {
  --ifm-alert-background-color: var(--ifm-color-warning-light);
}

.alert--danger {
  --ifm-alert-background-color: var(--ifm-color-danger-lighter);
}

```

Resources:
- https://infima.dev/docs/utilities/colors/

**Comment by abhi18av** [comment]
I'm closing up this PR since for the time being, after a discussion with Paolo, we have decided not to go ahead with this transition and improve the current docs.

**Pull request closed without merging**
