### PR TITLE
Update fonts

### PR DESCRIPTION
**Pull request by olehpratsko**

### CODE REVIEW

**Comment by pditommaso** [comment]
Nice restyling, a few notes: 

* Tip/Warning callouts title is a bit too big or at least should be aligned better with the icon 
* Also the text in the Tip/Warning callouts maybe is should be some points smaller compared to normal text. 
* Bold text both in Tip callout and in normal paragraph looks too tick 


Screenshot 2021-06-25 at 09 55 02

**Comment by abhi18av** [comment]
Hi @olehpratsko , 

Thanks for the updates on this!

It'd be great if we could finalize this PR and use the improvements in the docs :)

**Comment by olehpratsko** [comment]
Hi @abhi18av,
Sorry for the delay, I've adjusted styles as requested. Let me know if everything looks fine or you find any issues.

**Review by abhi18av — APPROVED** [review]
Hi @olehpratsko , 

To me it looks good to merge - what do you think @pditommaso ?

image

**Comment by pditommaso** [comment]
Much better! Thanks a lot.

**Pull request merged**
