### PR TITLE
Initial work for algolia integration

### PR DESCRIPTION
**Pull request by abhi18av**
This PR laids the groudwork for integrating `algolia` for the search functionality in the website.

Apparently, the creator of `mkdocs-material` isn't a big fan of `algolia` and there is no native support.  I had to do some Github code hunt.

References:
 - https://github.com/ManticoreGamesInc/platform-documentation/blob/f67a29d4af29bfdd157078dc309d8fbf1051bd12/algolia-config.json
- https://github.com/ManticoreGamesInc/platform-documentation/blob/development/mkdocs.yml

### CODE REVIEW

**Comment by pditommaso** [comment]
> Apparently, the creator of mkdocs-material isn't a big fan of algolia and there is no native support. 

and he's not the only one! 😄 what's the problem with the mkdocs search?

**Comment by abhi18av** [comment]
>  what's the problem with the mkdocs search?

The granularity of the search, for example when you were trying to search for `TOWER_WORKSPACE_ID` in the docs and even though it's mentioned on the introduction page, `native search` didn't pick it up.

**Comment by pditommaso** [comment]
There's  a pro/sponsored version of mkdocs with some extra features. Can you check if there's something improving the search experience?

**Comment by abhi18av** [comment]
Yeah, they offer a couple shiny things (among other features) for the pro (insiders) version.

image

**Comment by pditommaso** [comment]
Let's buy it!

**Comment by abhi18av** [comment]
Sounds good :) 

Though worth mentioning it works on a sponsorship model 

https://squidfunk.github.io/mkdocs-material/insiders/ 

image

**Comment by pditommaso** [comment]
Think we can afford 10 bucks per month! 😄

**Comment by abhi18av** [comment]
Of course 😄 

Then, I'll be closing this PR in favor of building upon the features of `mkdocs`.

**Pull request closed without merging**
