### PR TITLE
Add Tower Agent documentation

### PR DESCRIPTION
**Pull request by jordeu**

### CODE REVIEW

**Review by bentsherman — APPROVED** [review]

**Comment by gwright99** [comment]
How time-sensitive is this update? Meant to coincide with 22.2 release?

**Review by gwright99 — CHANGES_REQUESTED** [review]
Good first attempt but I think the content needs to be further expanded upon to avoid confusion.

1) Opening paragraphs should make it clearer that the Agent serves two roles: a workaround to locked down SSH cluster, and the ability to submit jobs as individuals rather than via a Service Account. This is noted as a throwaway in the last line of the paragraph, but I think should be make much clearer.

2) Unless the flow has changed, to create the credential in Tower requires the Agent to be first spun up in user space on the Cluster. There's a two step process here:

    1) First Actor (likely Workspace Power User): Need to activate the Agent in their HPC user space, then create the credential in Tower as the Agent is running and connected to Tower.
    
    nth) Actor: Install and activate Agent in their userspace, launch pipelines from Tower (without having to tinker with the credential which should already be created for them).
    
3) Elaborate upon work directory configuration - we saw Rijkzwaan had some major confusion getting this set up properly because of how they choose to use their folder structure. We should be more clear/prescriptive here or else I'm sure we'll get support calls.

4) Are there any connectivity behaviours sysadmins should be aware of? I recall seeing some recent tickets about the Agent disconnecting/reconnecting regularly. Normal or abnormality? 

5) How about port considerations (e.g. making it clear we use Websockets and need port 443)?

General question: What's the approach re: Agent documentation for help.tower.nf versus the documentation for the GitHub repo? Is the GH repo directing people to come read the material on help.tower.nf? We should not have different versions of Agent docs in different places.

**Comment by gwright99** [comment]
In case it helps, I can share some material that came out of an info session we did with @jordeu a few months ago: 
https://github.com/seqeralabs/support-backlog/blob/master/docs/content/diagrams/tower-agent.md

**Comment by abhi18av** [comment]
Guys, is there any blocker for the content of this PR? 

Perhaps we can address the rest of the changes via another issue/PR?

**Comment by bentsherman** [comment]
I guess that's fine if you think it's urgent to have at least something on the agent. Our next doc session is this Friday so Jordi will probably complete the work then.

**Comment by abhi18av** [comment]
Merging this to avoid stale PRs, but would be great if we can follow up on @gwright99  suggestions https://github.com/seqeralabs/nf-tower-docs/pull/212#pullrequestreview-1040535038 in a different PR.

Clients who opt for this, are quite interested in the underlying details.

**Pull request merged**
