### PR TITLE
Docs review for compute envs from Alejandra

### PR DESCRIPTION
**Pull request by abhi18av**
@ferralej, I've created a direct PR to the main repo for the docs with all your changes.

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Looks good! shall I merge?

**Review by abhi18av — COMMENTED** [review]
Minor fix

**Comment by abhi18av** [comment]
Yup, I built it locally to test - all looking good.

**Comment by pditommaso** [comment]
Cool thanks

**Pull request merged**
